train:
  result_save:
  mode:
  model_class:
  features_extractors:
    extractor_function_name: "extract_wifi_features"
      
      mall_id: ""
      features_prefix:
      wifi_info_cache_pre_fix: "../data/.."
      :

  features_prefix:
  result_prefix:
  hyperparameters:



